baseURL: https://cookbooktheme.elephantintheroom.dev
languageCode: en-us
title: Cookbook Theme Documentation
module:
  proxy: direct
  hugoVersion:
    extended: true
    min: 0.73.0
  imports:
    - path: github.com/google/docsy
      disable: false
    - path: github.com/google/docsy/dependencies
      disable: false
